name: Auto Test

on:
  push:
  pull_request:

jobs:
  auto-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 16.x]

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install StoreDown dependencies
      run: npm install

    - name: Build StoreDown artifacts
      run: npm run build

    - name: Run lint test
      run: npm run lint

    - name: Run e2e Tests
      run: npm run test:e2e
