name: Release

on:
  push:
    branches:
      - working # TODO

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    steps:
      #Based on https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
      - name: Set env 
        run: echo "RELEASE_VERSION=${jq -r .version package.json}" >> $GITHUB_ENV 
      - name: Test
        run: |
          echo $RELEASE_VERSION
          ls -lt dist


